######################################################################
# VTK Designer 2 - OsgParticle component
# 
# Autogenerated using VNFComponentGen
######################################################################

include(../Components.pri)

MOC_DIR         = $${PROJECT_BASE}/tmp/OsgParticle
OBJECTS_DIR     = $${PROJECT_BASE}/tmp/OsgParticle
UI_HEADERS_DIR  = $${PROJECT_BASE}/tmp/OsgParticle
RCC_DIR         = $${PROJECT_BASE}/tmp/OsgParticle
UI_DIR          = $${PROJECT_BASE}/tmp/OsgParticle

# Additional includes from the VTK system
INCLUDEPATH     += $${PROJECT_BASE}/Common

# Input
HEADERS += source/OsgParticleComponent.h \
           source/OsgSmokeEffectVisNode.h \
           source/OsgFireEffectVisNode.h \
           source/OsgExplosionEffectVisNode.h \
           source/OsgPrecipitationEffectVisNode.h \
           source/OsgBoxPlacerVisNode.h \
           source/OsgCenteredPlacerVisNode.h \
           source/OsgConnectedParticleSystemVisNode.h \
           source/OsgForceOperatorVisNode.h \
           source/OsgParticleVisNode.h \
           source/OsgPointPlacerVisNode.h \
           source/OsgRadialShooterVisNode.h \
           source/OsgSectorPlacerVisNode.h \
           source/OsgSegmentPlacerVisNode.h \
           source/OsgRandomRateCounterVisNode.h \
           source/OsgVariableRateCounterVisNode.h \
           source/OsgModularEmitterVisNode.h \
 

SOURCES += source/OsgParticleComponent.cpp \
           source/OsgSmokeEffectVisNode.cpp \
           source/OsgFireEffectVisNode.cpp \
           source/OsgExplosionEffectVisNode.cpp \
           source/OsgPrecipitationEffectVisNode.cpp \
           source/OsgBoxPlacerVisNode.cpp \
           source/OsgCenteredPlacerVisNode.cpp \
           source/OsgConnectedParticleSystemVisNode.cpp \
           source/OsgForceOperatorVisNode.cpp \
           source/OsgParticleVisNode.cpp \
           source/OsgPointPlacerVisNode.cpp \
           source/OsgRadialShooterVisNode.cpp \
           source/OsgSectorPlacerVisNode.cpp \
           source/OsgSegmentPlacerVisNode.cpp \
           source/OsgRandomRateCounterVisNode.cpp \
           source/OsgVariableRateCounterVisNode.cpp \
           source/OsgModularEmitterVisNode.cpp \


# VNFComponentGen has generated an empty resource file. If you add
# new objects to the resource file, then you can uncomment the line
# below
RESOURCES += OsgParticle.qrc

# Nodes in VTK Designer 2 have to implement one or more node interfaces
# Implementing all of them from scratch would be a tough task. So, we make
# use of ready made implementations and then subclass from them.
HEADERS   +=  $${PROJECT_BASE}/Common/CGenericVisNodeDesc.h \
              $${PROJECT_BASE}/Common/CGenericVisNodeBase.h 

SOURCES   +=  $${PROJECT_BASE}/Common/CGenericVisNodeDesc.cpp \
              $${PROJECT_BASE}/Common/CGenericVisNodeBase.cpp 


            
