######################################################################
# VTK Designer 2 - OsgShadow component
# 
# Autogenerated using VNFComponentGen
######################################################################

include(../Components.pri)


MOC_DIR         = $${PROJECT_BASE}/tmp/OsgShadow
OBJECTS_DIR     = $${PROJECT_BASE}/tmp/OsgShadow
UI_HEADERS_DIR  = $${PROJECT_BASE}/tmp/OsgShadow
RCC_DIR         = $${PROJECT_BASE}/tmp/OsgShadow
UI_DIR          = $${PROJECT_BASE}/tmp/OsgShadow

# Additional includes from the VTK system
INCLUDEPATH     += $${PROJECT_BASE}/Common

# Input
HEADERS += source/OsgShadowComponent.h \
           source/OsgOccluderGeometryVisNode.h \
 

SOURCES += source/OsgShadowComponent.cpp \
           source/OsgOccluderGeometryVisNode.cpp \


# VNFComponentGen has generated an empty resource file. If you add
# new objects to the resource file, then you can uncomment the line
# below
RESOURCES += OsgShadow.qrc

# Nodes in VTK Designer 2 have to implement one or more node interfaces
# Implementing all of them from scratch would be a tough task. So, we make
# use of ready made implementations and then subclass from them.
HEADERS   +=  $${PROJECT_BASE}/Common/CGenericVisNodeDesc.h \
              $${PROJECT_BASE}/Common/CGenericVisNodeBase.h 

SOURCES   +=  $${PROJECT_BASE}/Common/CGenericVisNodeDesc.cpp \
              $${PROJECT_BASE}/Common/CGenericVisNodeBase.cpp 


            
