######################################################################
# VTK Designer 2 - OsgFX component
# 
# Autogenerated using VNFComponentGen
######################################################################

include(../Components.pri)

MOC_DIR         = $${PROJECT_BASE}/tmp/OsgFX
OBJECTS_DIR     = $${PROJECT_BASE}/tmp/OsgFX
UI_HEADERS_DIR  = $${PROJECT_BASE}/tmp/OsgFX
RCC_DIR         = $${PROJECT_BASE}/tmp/OsgFX
UI_DIR          = $${PROJECT_BASE}/tmp/OsgFX

# Additional includes from the VTK system
INCLUDEPATH     += $${PROJECT_BASE}/Components/VTKSystem/Interfaces \
                   $${PROJECT_BASE}/Components/VTKSystem/IOData \
                   $${PROJECT_BASE}/Common

# Input
HEADERS += source/OsgFXComponent.h \
           source/OsgAnisotropicLightingVisNode.h \
           source/OsgBumpMappingVisNode.h \
           source/OsgCartoonVisNode.h \
           source/OsgMultiTextureControlVisNode.h \
           source/OsgScribeVisNode.h \
           source/OsgSpecularHighlightsVisNode.h \
 

SOURCES += source/OsgFXComponent.cpp \
           source/OsgAnisotropicLightingVisNode.cpp \
           source/OsgBumpMappingVisNode.cpp \
           source/OsgCartoonVisNode.cpp \
           source/OsgMultiTextureControlVisNode.cpp \
           source/OsgScribeVisNode.cpp \
           source/OsgSpecularHighlightsVisNode.cpp \

LIBS			+= -losgd \
				-losgGAd \
				-losgViewerd \
				-losgDBd \
				-lQtGuid4 \
				-lQtCored4 \
				-lQtOpenGLd4 \

# VNFComponentGen has generated an empty resource file. If you add
# new objects to the resource file, then you can uncomment the line
# below
RESOURCES += OsgFX.qrc

# Nodes in VTK Designer 2 have to implement one or more node interfaces
# Implementing all of them from scratch would be a tough task. So, we make
# use of ready made implementations and then subclass from them.
HEADERS   +=  $${PROJECT_BASE}/Common/CGenericVisNodeDesc.h \
              $${PROJECT_BASE}/Common/CGenericVisNodeBase.h 

SOURCES   +=  $${PROJECT_BASE}/Common/CGenericVisNodeDesc.cpp \
              $${PROJECT_BASE}/Common/CGenericVisNodeBase.cpp 


